substitutions:
  name: "intex-pure-spa"
  friendly_name: "Intex Pure Spa"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  #name_add_mac_suffix: true
  project:
    name: UlrichMai.esphome-intex-pure-spa
    version: "1.0"
  platformio_options:
    board_build.f_cpu: 160000000L

esp8266:
  board: d1_mini

external_components:
  - source: github://UlrichMai/esphome-intexsbh20
    components: [intexsbh20]

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

#dashboard_import:
#  package_import_url: github://UlrichMai/esphome-intexsbh20/intex-pure-spa.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret wifi_ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s 
    entity_category: diagnostic

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic 
    
climate:

switch:

text_sensor:

intexsbh20:
  climate:
    name: Thermostat
    icon: mdi:hot-tub
  power:
    name: Power
    icon: mdi:power
  filter:
    name: Filter
    icon: mdi:air-filter
  bubble:
    name: Bubble
    icon: mdi:chart-bubble
  water_temperature:
    name: Water temperature
    icon: mdi:water-thermometer
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 0
    unit_of_measurement: °C
  error_text:
    name: Error
    icon: mdi:alert-circle
    entity_category: diagnostic
