esphome:
  name: intex-pure-spa
  friendly_name: Intex Pure Spa
  platformio_options:
    board_build.f_cpu: 160000000L

esp8266:
  board: d1_mini

external_components:
  - source:
      type: local
      path: components

logger:

api:
  encryption:
    key: "..."

ota:
  password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

climate:

switch:

text_sensor:

intexsbh20:
  climate:
    name: Thermostat
  power:
    name: Power
  filter:
    name: Filter
  bubble:
    name: Bubble
  error_text:
    name: Error
